---
- name: BUILD APPS
  hosts: all
  tasks:
    - name: Run Maven clean package in production mode
      shell: mvn clean package -DskipTests -Pproduction
      args:
        chdir: /root/fenanza/fenanza-be